[features]
seeds = true
skip-lint = false
[programs.devnet]
merkle_distributor = "9d8qmkJoNrbutopEM2dEE4HQudVZXdz1VoBYnj1LHkgN"

[programs.localnet]
merkle_distributor = "9d8qmkJoNrbutopEM2dEE4HQudVZXdz1VoBYnj1LHkgN"

[programs.mainnet]
merkle_distributor = "9d8qmkJoNrbutopEM2dEE4HQudVZXdz1VoBYnj1LHkgN"

[programs.testnet]
merkle_distributor = "9d8qmkJoNrbutopEM2dEE4HQudVZXdz1VoBYnj1LHkgN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/merkle-distributor"]

[scripts]
test = "yarn mocha"
