[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
merkle_distributor = "HQAZCrahgetT453VM2WUX4TSgV98xMrJ1L2SWwd6vrZB"

[programs.localnet]
merkle_distributor = "HQAZCrahgetT453VM2WUX4TSgV98xMrJ1L2SWwd6vrZB"

[programs.mainnet]
merkle_distributor = "HQAZCrahgetT453VM2WUX4TSgV98xMrJ1L2SWwd6vrZB"

[programs.testnet]
merkle_distributor = "HQAZCrahgetT453VM2WUX4TSgV98xMrJ1L2SWwd6vrZB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keypairs/admin-keypair.json"

[workspace]
members = ["programs/merkle-distributor"]

[scripts]
test = "yarn mocha"
